### lightgbm

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score


### 数据集

In [2]:
iris = datasets.load_iris()
data = iris.data
label = iris.target

# data.shape, label.shape

data1 = pd.DataFrame(data)
data1.columns = ['sepal_l', 'sepal_w', 'petal_l', 'petal_w']
label1 = pd.DataFrame(label)
label1.colums = ['label']
# data1.head(), label1.head()

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  # Remove the CWD from sys.path while we load stuff.


In [3]:
train_x, test_x, train_y, test_y = train_test_split(data, label, test_size = 0.3)
train_x.shape, test_x.shape,train_y.shape, test_y.shape 

((105, 4), (45, 4), (105,), (45,))

In [19]:
lgb.train?

In [4]:
train_x, test_x, train_y, test_y = train_test_split(data1, label1, test_size = 0.3)

train_data = lgb.Dataset(train_x, train_y)
test_data = lgb.Dataset(test_x, test_y)

lgb_params = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'metric': 'multi_error',
    'verbose': 1,
    'num_class': 3
}
clf = lgb.train(lgb_params, train_data, num_boost_round = 10,
               valid_sets = [train_data, test_data],
               verbose_eval = 10)
test_pre = clf.predict(test_x, num_iteration=clf.best_iteration)
test_pre_1 = np.asarray([np.argmax(row) for row in test_pre])
print('Accuracy: ', precision_score(test_y, test_pre_1, average='macro'))
print('Recall: ', recall_score(test_y, test_pre_1, average='macro'))

[10]	training's multi_error: 0.0285714	valid_1's multi_error: 0.0888889
Accuracy:  0.9077380952380952
Recall:  0.9166666666666666


In [5]:
test_pre

array([[0.14864831, 0.69232755, 0.15902413],
       [0.13565964, 0.12921561, 0.73512475],
       [0.14938692, 0.69458088, 0.1560322 ],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.13565964, 0.12921561, 0.73512475],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.14286181, 0.12813891, 0.72899928],
       [0.1363404 , 0.28030289, 0.58335671],
       [0.15594207, 0.17775225, 0.66630569],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.13565964, 0.12921561, 0.73512475],
       [0.14286181, 0.12813891, 0.72899928],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.1558901 , 0.17776319, 0.66634671],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.14286181, 0.12813891, 0.72899928],
       [0.14868477, 0.69229791, 0.15901732],
       [0.72226503, 0.1288562 , 0.14887877],
       [0.16162564, 0.67593785, 0.16243651],
       [0.14868477, 0.69229791, 0.15901732],
       [0.20964519, 0.64537608, 0.14497873],
       [0.

In [6]:
test_pre_1

array([1, 2, 1, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0,
       2], dtype=int64)

In [21]:
recall_score?

In [7]:
#### Sklearn接口形式的lightgbm
lgb_params = {
    'learning_rate': 0.1,
    'max_bin': 150,
    'num_leaves': 32,
    'max_depth': 11,
    'objective': 'multiclass',
    'n_estimators': 300
}
model = lgb.LGBMClassifier(**lgb_params)
model.fit(train_x, train_y)
test_pre2 = model.predict(test_x)
print('Accuracy: ', precision_score(test_y, test_pre2, average='macro'))
print('Recall: ', recall_score(test_y, test_pre2, average='macro'))

Accuracy:  0.9291101055806937
Recall:  0.9351851851851851


D:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [20]:
model.fit?

In [8]:
test_pre2

array([1, 2, 1, 0, 0, 2, 0, 2, 1, 2, 0, 2, 2, 0, 2, 0, 2, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0,
       2])

In [9]:
lgb.train?

#### xgboost

In [10]:
import xgboost as xgb

In [11]:
train_x, test_x, train_y, test_y = train_test_split(data, label, test_size = 0.3)
train_x.shape, test_x.shape,train_y.shape, test_y.shape 

((105, 4), (45, 4), (105,), (45,))

In [12]:
test_data = xgb.DMatrix(test_x, label=test_y)
xgb_params = {
    'eta': 0.3,
    'silent': True,
    'objective': 'multi:softprob',
    'num_class': 3,
    'max_depth': 3
}
num_round = 20
model = xgb.train(xgb_params, xgb.DMatrix(train_x, label=train_y), num_round)
test_pre = model.predict(test_data)
test_pre_1 = np.asarray([np.argmax(row) for row in test_pre])
print('Accuracy: ', precision_score(test_y, test_pre_1, average='macro'))
print('Recall: ', recall_score(test_y, test_pre_1, average='macro'))

Accuracy:  0.9077380952380952
Recall:  0.9166666666666666


### Sklearn形式

In [13]:
from xgboost import XGBClassifier

In [14]:
model = XGBClassifier(learning_rate = 0.01, n_estimators=300, max_depth = 4,
                     objective='binary:logistic', seed=27)
model.fit(train_x, train_y)
test_pre2 = model.predict(test_x)
print('Accuracy: ', precision_score(test_y, test_pre2, average='macro'))
print('Recall: ', recall_score(test_y, test_pre2, average='macro'))

Accuracy:  0.9077380952380952
Recall:  0.9166666666666666
