In [16]:
def MyRange(end):
    start = 0
    while start < end:
        x = yield start
        #x = start
        print(x)
        start+=1

In [17]:
m = MyRange(8)
type(m),next(m),next(m)

None


(generator, 0, 1)

In [2]:
import re


In [3]:
textString = "文本最重要的来源无疑是网络，我们要把网络中的文本获取形成一个文本数据库。利用一个爬虫抓取到网络中的信息，爬取的策略有广度爬取和深度爬取。根据用户的需求，爬虫可以有主题爬虫和通用爬虫之分"
pString = re.split('，|。',textString)
#print(pString)

In [4]:
regex = '^爬'
#regex = '网络$'
#regex = '^文本'
for line in pString:
    if re.search(regex,line) is not None:
        print(line)

爬取的策略有广度爬取和深度爬取
爬虫可以有主题爬虫和通用爬虫之分


In [5]:
if re.search(r"\\","I have one nee\dle"):
    print("Match it ")
else:
    print("not match")


Match it 


In [6]:
strings = ['War of 1812','There are 5280 feet to a mile','Happ New Year 2019']
for s in strings:
    if re.search('[1-2][0-9]{3}',s):
        print(s)

War of 1812
Happ New Year 2019


In [7]:
re.findall('[a-z]{3}','abc1234')

['abc']

In [8]:
text = "2016 was a good year, but 2017 will be better!"
re.findall('[2][0-9]{3}',text)

['2016', '2017']

In [9]:
import numpy as np

In [10]:
vector = np.arange(9).reshape(3,3)
print(vector)
vector[:,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([1, 4, 7])

In [11]:
ve = vector == 1

In [12]:
vector.sum(axis=1)

array([ 3, 12, 21])

In [13]:
fileName = "D:\python\datasource\data.csv"

In [14]:
class MaxMatch:
    def __init__(self,dicPath):
        self.dic = set()
        self.maxSize = 0
        with open(dicPath,'r',encoding='utf8') as f:
            for line in f:
                line = line.strip()
                if line:
                    #print(line)
                    self.dic.add(line)
                    #self.maxSize = len(line)
                    if self.maxSize < len(line):
                        self.maxSize = len(line)
    def backwardCut(self,text):
        result = []
        index = len(text)
        while index > 0:
            word = None
            for size in range(self.maxSize,0,-1):
                if index - size < 0:
                    size = index
                piece = text[(index-size):index]
                #print(piece)
                if piece in self.dic:
                    word = piece
                    result.append(word)
                    index -= size
                    break
            if word is None:
                result.append(text[index-1])
                index -= 1
        return result[::-1] 
    def forwardCut(self,text):
        result = []
        index = 0
        textLen = len(text)
        while(index<textLen):
            for size in range(self.maxSize,0,-1):
                word = None
                if index+size > textLen:
                    size = textLen-index
                piece = text[index:index+size]
                #print(piece)
                if piece in self.dic:
                    word = piece
                    result.append(word)
                    index += size
                    break
            if word is None:
                result.append(text[index])
                index += 1
        return result
    def binCut(self,text):
        backResult = self.backwardCut(text)
        forResult = self.forwardCut(text)
        if len(backResult) > len(forResult):
            return forResult
        else:
            return backResult

In [15]:
dicFile = 'D:\python\datasource\imm_dic.utf8'
dicFile = 'D:\python\datasource\imm_dic.utf8'
text = "南京市长江大桥人民解放军英雄纪念碑"
tokenizer = MaxMatch(dicFile)


In [16]:
print(tokenizer.forwardCut(text))

['南京市长', '江', '大桥', '人民解放军', '英雄纪念碑']


In [17]:
print(tokenizer.backwardCut(text))

['南京市', '长江大桥', '人民解放军', '英雄纪念碑']


In [18]:
print(tokenizer.binCut(text))

['南京市', '长江大桥', '人民解放军', '英雄纪念碑']


In [19]:
print(tokenizer.dic)
print(tokenizer.maxSize)

{'南京市长', '国家', '人民', '南京市', '国家大剧院', '人民解放军', '长江大桥', '大桥', '英雄纪念碑'}
5


In [20]:
dicPath = 'D:\python\datasource\imm_dic.utf8'
dic = ['长江大桥', '人民解放军', '大桥', '南京市', '南京市长','国家','国家大剧院']
dic.append('英雄纪念碑')
dic.append('人民')
with open(dicPath,'w',encoding='utf8') as f:
    for line in dic:
        line = line.strip()
        if line:
            f.write(line+'\n')